import type { Metadata } from "next";
import "./styles/globals.css";
import { Toaster } from "sonner";
import { Rubik } from "next/font/google";
import logo from "../assets/icon/navbar/logo.png";

const fontStyle = Rubik({ subsets: ["cyrillic"], weight: "400" });
export const metadata: Metadata = {
  title: "Nusarasa",
  description: "Generated by create next app",
  icons: `${logo}`,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fontStyle.className}>
        {" "}
        <Toaster position="top-center" closeButton richColors expand={false} />
        {children}
      </body>
    </html>
  );
}
