import type { Metadata } from "next";
import "./styles/globals.css";
import { Toaster } from "sonner";
import { Rubik } from "next/font/google";
import dynamic from "next/dynamic";
import logo from "@/assets/icon/navbar/logo.png";
import NavBar from "@/components/pages/navbar/navbar";
import NextAuthProvider from "@/components/provider/nextauth";

const ProgressBar = dynamic(() => import("@/components/progress-bar/index"), {
  ssr: false,
});

const fontStyle = Rubik({ subsets: ["cyrillic"], weight: "400" });

export const metadata: Metadata = {
  title: "Nusarasa",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: logo.src }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fontStyle.className}>
        <ProgressBar />
        <NextAuthProvider>
          <Toaster
            position="top-center"
            closeButton
            richColors
            expand={false}
          />
          <NavBar />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
